### ISSUE TITLE
Invoke-PowerBIRestMethod - Basic Authentication with password from AzureKeyvault

### ISSUE THREAD

**Issue by ktdixit** [jayendranarumugam/PowerBI-CICD#4]
Hi Jayendra, 

Could you please let me know the procedure to pass the values from AzureKeyvault Secret into "**Password**"

**Error:**
**_Invoke-PowerBIRestMethod -Url "gateways/$($BounGateway.value.gatewayI … One or more errors occurred. (Response status code does not indicate success: 400 (Bad Request).)_**

**Script:**

#**$(Password)** can be from AzureKeyvault or from secret variable in Azure Pipelines
$SecretvalueText = **$(Password)** | ConvertTo-SecureString -AsPlainText -Force
$BounGateway=Invoke-PowerBIRestMethod -Url "groups/**_WorkspaceID_**/datasets/**_DataSetID_**/Default.GetBoundGatewayDataSources" -Method GET | ConvertFrom-Json
$UpdateUserCredential = @{
      credentialType ="Basic"
      basicCredentials = @{            
      username= $(UserName) //AzureDevOps Pipeline Variable
      password= $SecretvalueText 
  }
Invoke-PowerBIRestMethod -Url "gateways/$($BounGateway.value.gatewayId)/datasources/$($BounGateway.value.id)" -Method PATCH -Body $UpdateUserCredential | ConvertFrom-Json
} | ConvertTo-Json

**Comment by jayendranarumugam** [comment]
The way I used this script using AzureDevOps Pipeline (for CICD), which has an easier way to retrieve the secrets from keyvault directly (without PowerShell), I explained that [here](https://jayendranarumugam.wordpress.com/2019/06/19/azuredevops-deploying-secrets-from-azure-pipelines/).  I also mentioned this in the comment of the script like 

> $applicationId = "" # Need to pass the clientid from devops variable 
$password= "Password@123" # Need to pass from devops secret variable  

If you want to use this script elsewhere then you can refer [here with powershell way](https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-powershell#retrieve-a-secret-from-key-vault)

**Comment by ktdixit** [comment]
@jayendranarumugam please let me know how do you call a secret variable to pass in "UpdateUserCredential". Are you suggesting below method? 
$SecretvalueText = "$(Password)" | ConvertTo-SecureString -AsPlainText -Force //Password from AzureDevOps Secret variable? 

this didnt work. Please elaborate on your 2nd approach (Powershell Way). Do you recommend AzurePowershell or Powershell in AzureDevOps Pipeline Tasks?

**Comment by jayendranarumugam** [comment]
> this didnt work

What do you mean by didn't work? Any error? Did you try to solve it? 

I didn't try the second approach, so I couldn't really comment on that. Usually, It is recommended to use AzurePowershell rather than PowerShell if you want to do more operations on azure resources, which takes care of the authentications.

On the other hand , I can see that there is also a [native task and method recommended by Microsoft](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops) to retrieve the secret from keyvault in azure DevOps (without Powershell)

**Comment by ktdixit** [comment]
@jayendranarumugam when I use Powershell Task in AzureDevOps, script works but have to hardcode the DBPassword
When I use AzurePowershell, I am getting the below error: 
**_Attempted to access an element as a type incompatible with the array_**

**Comment by ktdixit** [comment]
working
