### ISSUE TITLE
Report Deployment in .rdl format

### ISSUE THREAD

**Issue by ktdixit** [jayendranarumugam/PowerBI-CICD#5]
@jayendranarumugam could you please guide on how to deploy **.rdl file** developed from PowerBI Report Builder tool? I am able to deploy report file in .pbix format developed from PowerBI Desktop, but looking for .rdl file deployment.

**Comment by jayendranarumugam** [comment]
I do not have much experience in Reporting servers. But doing some googling I got some links for you below

- [Github Example](https://github.com/microsoft/Reporting-Services/blob/master/APISamples/powershell/powershellSamples.ps1) 

> ```powershell
> $ReportPortalUri = 'http://myserver/reports'
> 
> Write-Host "Upload an item..."
> $uploadItemPath = 'C:\reports\test.rdl'
> $catalogItemsUri = $ReportPortalUri + "/api/v2.0/CatalogItems"
> $bytes = [System.IO.File]::ReadAllBytes($uploadItemPath)
> $payload = @{
>     "@odata.type" = "#Model.Report";
>     "Content" = [System.Convert]::ToBase64String($bytes);
>     "ContentType"="";
>     "Name" = 'test';
>     "Path" = '/test';
>     } | ConvertTo-Json
> Invoke-WebRequest -Uri $catalogItemsUri -Method Post -Body $payload -ContentType "application/json" -UseDefaultCredentials | Out-Null
> 
> 
> Write-Host "Download an item..."
> $downloadPath = 'C:\download\test.rdl'
> $catalogItemsApi = $ReportPortalUri + "/api/v2.0/CatalogItems(Path='/test')/Content/$value"
> $url = [string]::Format($catalogItemsApi, $item)
> $response = Invoke-WebRequest -Uri $url -Method Get -UseDefaultCredentials
> [System.IO.File]::WriteAllBytes($downloadPath, $response.Content)
> 
> 
> Write-Host "Delete an item..."
> $url = $ReportPortalUri + "/api/v2.0/CatalogItems(Path='/test')"
> Invoke-WebRequest -Uri $url -Method Delete -UseDefaultCredentials | Out-Null
> ```


- [Documentation Swagger for PBRS API's](https://app.swaggerhub.com/apis/microsoft-rs/PBIRS/2.0)

**Comment by ktdixit** [comment]
Thanks @jayendranarumugam . We use PowerBI Report Builder (.rdl) to deploy the file to PowerBI workspace manually. So, was checking for any script to automate deployment to other environments.

**Comment by jayendranarumugam** [comment]
You could try the script which I was provided above.

**Comment by jayendranarumugam** [comment]
Closing this as there is no response. Feel free to add a comment if you need help
