### ISSUE TITLE
Power Bi CICD : issue with CD process

### ISSUE THREAD

**Issue by nikmk05** [jayendranarumugam/PowerBI-CICD#6]
Hi 
I am working on CICD in power bi using Azure devops and CI process is perfectly working. But for the CD process i am using Master account auth type and using Power bi actions extension to upload pbix file to Power Bi workspace.

So i am getting error while releasing stage after deploying.(one or more error)

Actually i am having  Power Bi pro  License  and trying to upload the file to that workspace.

Please can you guide me to what type of workspace is used to upload the file and what are the settings and requirments.

Thanks.
Nikhil M K

**Comment by jayendranarumugam** [comment]
Hi Nikhil, If you are getting the error from the powerbi action, I'd recommend checking the existing or creating a new issue on https://github.com/maikvandergaag/msft-extensions/issues so you can be on the right path.

Coming to your question, the Only requirement I could think of is the service account that you are using should have admin access to the workspace

**Comment by nikmk05** [comment]
Hi
Thanks for getting back to me.
Thanks for your support.
