### ISSUE TITLE
Unable to Refresh, Takeover Dataset

### ISSUE THREAD

**Issue by jyothsnakundan** [jayendranarumugam/PowerBI-CICD#8]
Hi Jayendran,

Thanks for the wonderful post.
I have tried your steps.
When I'm trying to takeover dataset,refresh the dataset and apply schdeule refresh, its throwing errors as SPN is not having access.
DO we need to add the SPN to Gateway similar to User PrincipalName.
And Does the cloud sources also needs to be added with SPN to Gateway.

Thanks in advance.

Regards,
Srinivas K

**Comment by jayendranarumugam** [comment]
Hi @jyothsnakundan , If you are talking about dataset that using cloud source then there is no gateway is needed - such a scenario if you add the spn as workspace admin all dataset operations will work

If you have a dataset that is using on-prem or need a gateway (to refresh) then your SPN should have access to the gateway. There is a way to add the SPN as admin to the gateway https://learn.microsoft.com/en-us/powershell/module/datagateway/add-datagatewayclusteruser?view=datagateway-ps#example-4

But I remember from my earlier days when they released these features of adding SPN to gateway there are some limitation which I captured here https://github.com/jayendranarumugam/GatewayAutomation/blob/master/README.md#limitation-as-of-may-2020 I personally never tried this so not sure how it will work for you now.

**Comment by jayendranarumugam** [comment]
@jyothsnakundan I'm closing this issue for now. If you need any further help let me know
